<div class="content">
        <?php View::content() ?>
        <h3>Alta de Turnos</h3>

        <?= Form::open(); // por defecto llama a la misma url 
        ?>

        <label> Alumno o Piloto
                <?= Form::number('Turnos.id_piloto') ?></label>
        <label> Aeronave
                <?= Form::number('Turnos.id_aeronave') ?></label>
        <label>Categoria
                <?= Form::text('Turnos.categoria') ?></label>
        <label>Hora de Inicio
                <?= Form::time('Turnos.hora_inicio') ?></label>
        <label>Hora de Fin
                <?= Form::time('Turnos.hora_fin') ?></label>
        <label>Duracion
                <?= Form::number('Turnos.duracion') ?></label>

        <?= Form::submit('Agregar') ?>

        <?= Form::close() ?>
</div>