<div class="content">
        <?php View::content() ?>
        <h3>Alta de Turnos</h3>

        <?= Form::open(); // por defecto llama a la misma url 
        ?>

        <label> Alumno o Piloto
                <?= Form::text('Turnos.marca') ?></label>

        <label>Categoria
                <?= Form::text('Turnos.categoria') ?></label>
        <label>Hora de Inicio
                <?= Form::date('Turnos.hora_inicio') ?></label>
        <label>Hora de Fin
                <?= Form::text('Turnos.hora_fin') ?></label>



        <?= Form::submit('Agregar') ?>

        <?= Form::close() ?>
</div>