<div class="content">
    <?php View::content() ?>


    <div class="barraCategoria">
        <h3 class="tituloCategoria">Turnos</h3>
        <i class="fa fa-plus-circle icono-categoria" aria-hidden="true"><?= Html::linkAction("alta/", ' Nuevo') ?></i>
    </div>

    <table>
        <th>Alumno o Piloto</th>
        <th>ID Aeronave</th>
        <th>Categoria</th>
        <th>Hora de Inicio</th>
        <th>Hora de Fin</th>
        <th>Duracion</th>
        <th colspan="2">Acciones</th>
        <?php foreach ($listTurno->items as $Turno) : ?>
            <tr>
                <td><strong><?= $Turno->Alumno ?> </strong></td>
                <td><strong> <?= $Turno->id_aeronave ?> </strong></td>
                <td><strong> <?= $Turno->categoria ?> </strong></td>
                <td><strong> <?= $Turno->hora_inicio ?> </strong></td>
                <td><strong> <?= $Turno->hora_fin ?> </strong></td>
                <td><strong> <?= $Turno->duracion ?> </strong></td>
                <td><?= Html::linkAction("modif/$Turno->id/", 'Editar') ?> </td>
                <td><?= Html::linkAction("baja/$Turno->id/", 'Borrar') ?> </td>
            </tr>
        <?php endforeach ?>
    </table>

    <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if ($listTurno->prev) echo Html::linkAction("index/$listTurno->prev/", '<< Anterior |') ?>
    <?php if ($listTurno->next) echo Html::linkAction("index/$listTurno->next/", 'Próximo >>') ?>
</div>