<div class="content">
        <?php View::content() ?>
        <h3>Alta de pilotos</h3>

        <?= Form::open(); // por defecto llama a la misma url 
        ?>

        <label>Nombre
                <?= Form::text('pilotos.nombre') ?></label>

        <label>Precio
                <?= Form::text('pilotos.precio') ?></label>



        <?= Form::submit('Agregar') ?>

        <?= Form::close() ?>
</div>