<div class="content">
        <?php View::content() ?>
        <h3>Editar Pilotos</h3>

        <?= Form::open(); // por defecto llama a la misma url 
        ?>
        <label>Nombre
                <?= Form::text('Pilotos.nombre') ?></label>

        <label>Apellido
                <?= Form::text('Pilotos.apellido') ?></label>
        <label>DNI
                <?= Form::text('Pilotos.dni') ?></label>
        <label>Fecha de Nacimiento
                <?= Form::date('Pilotos.fecha_nacimiento') ?></label>
        <label>Vencimiento de Licencia
                <?= Form::date('Pilotos.fecha_vencimiento_licencia') ?></label>
        <label>Categoria

                <?= Form::select('Pilotos.categoria', $categorias) ?></label>
        <label>Es instructor
                <?= Form::check('Pilotos.es_instructor', 1, null, ($Pilotos->es_instructor == 1)) ?></label>
        <label>Cantidad de Horas voladas
                <?= Form::number('Pilotos.cantidad_horas_voladas_piloto') ?></label>


        <?= Form::hidden('Pilotos.id') ?>
        <?= Form::submit('Actualizar') ?>

        <?= Form::close() ?>
</div>