    <h2>Cómo empezar con el framework KumbiaPHP</h2>
    <p>En la <a href="https://wiki.kumbiaphp.com/">wiki de Kumbia</a> podrás encontrar información actualizada sobre el uso del framework,
    si estas comenzando con <em>KumbiaPHP</em> deberías realizar  la
    <strong><a href="https://wiki.kumbiaphp.com/Hola_Mundo_KumbiaPHP_Framework">Aplicación Hola Mundo</a></strong>.</p>
    <p>También puede interesarte saber sobre:</p>
	<ul>
		<li><a href="https://wiki.kumbiaphp.com/V1.0_CRUD_en_KumbiaPHP_Framework">Creacion de CRUD(Create, Read, Update, Delete)</a></h3></li>
		<li><a href="https://wiki.kumbiaphp.com/Como_Usar_los_Modelos_en_KumbiaPHP">Uso de modelos</a></li>
		<li><a href="https://github.com/KumbiaPHP/Documentation/blob/master/es/active-record.md#configurando-conexi%C3%B3n-a-la-base-de-datos">Configurar conexiones a bases de datos</a></li>
	</ul>
	<p>Estos son sólo algunos ejemplos, puedes ver más en la <a href="https://wiki.kumbiaphp.com/Categor%C3%ADa:Tutoriales_KumbiaPHP" title="Tutoriales KumbiaPHP">sección de tutoriales de la wiki</a></p> 
        
        