<div class="content">
<?php View::content() ?>
<h3>Editar Cliente<h3>
 
 
<?= Form::open(); // por defecto llama a la misma url ?>
 
        <label>Nombre
        <?= Form::text('clientes.nombre') ?></label>
 
        <label>Apellido
        <?= Form::text('clientes.apellido') ?></label>
 
		<label>DNI
        <?= Form::text('clientes.dni') ?></label>
 
        <?= Form::hidden('clientes.id') ?>
        <?= Form::submit('Actualizar') ?>
 
<?= Form::close() ?>
</div>