<div class="content">
    <?php View::content() ?>


    <div class="barraCategoria">
        <h3 class="tituloCategoria">Alumnos:</h3>
        <i class="fa fa-plus-circle icono-categoria" aria-hidden="true"><?= Html::linkAction("alta/", ' Nuevo') ?></i>
    </div>

    <table>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>DNI</th>
        <th>Fecha de Nacimiento</th>
        <th>Fecha Inicio Curso</th>
        <th>Cantidad de Horas Voladas Alumno</th>
        <th colspan="2">Acciones</th>
        <?php foreach ($listAlumno->items as $alumno) : ?>
            <tr>
                <td><strong><?= $alumno->nombre ?> </strong></td>
                <td><strong> <?= $alumno->apellido ?> </strong></td>
                <td><strong> <?= $alumno->dni ?> </strong></td>
                <td><strong> <?= $alumno->fechaNacimiento?> </strong></td>
                <td><strong> <?= $alumno->fechaInicioCurso ?> </strong></td>
                <td><strong> <?= $alumno->cantidadHorasVoladasAlumno  ?> </strong></td>
                <td><?= Html::linkAction("modif/$alumno->id/", 'Editar') ?> </td>
                <td><?= Html::linkAction("baja/$alumno->id/", 'Borrar') ?> </td>
            </tr>
        <?php endforeach ?>
    </table>

    <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if ($listAlumno->prev) echo Html::linkAction("index/$listAlumno->prev/", '<< Anterior |') ?>
    <?php if ($listAlumno->next) echo Html::linkAction("index/$listAlumno->next/", 'Próximo >>') ?>
</div>