<div class="content">
        <?php View::content() ?>
        <h3>Editar Alumnos:</h3>


        <?= Form::open(); // por defecto llama a la misma url 
        ?>

        <label>Nombre
                <?= Form::text('Alumnos.nombre') ?></label>
        <label>Apellido
                <?= Form::text('Alumnos.apellido') ?></label>
        <label>DNI
                <?= Form::text('Alumnos.dni') ?></label>
        <label>Fecha de Nacimiento
                <?= Form::date('Alumnos.fechaNacimiento') ?></label>
        <label>Fecha de Inicio de Curso
                <?= Form::date('Alumnos.fechaInicioCurso') ?></label>
        <label>Cantidad de Horas Voladas Alumnos
                <?= Form::text('Alumnos.cantidad_horas_voladas_alumno') ?></label>

        <?= Form::hidden('Alumnos.id') ?>
        <?= Form::submit('Actualizar') ?>

        <?= Form::close() ?>
</div>